### ISSUE TITLE
Create a binary entry point

### ISSUE THREAD

**Issue by bgourlie** [bgourlie/asm6502#4]
This assembler is currently a library so it's not really usable out-of-the-box. It would be nice to provide a binary as part of this crate ([See this SO question](http://stackoverflow.com/questions/26946646/rust-package-with-both-a-library-and-a-binary) for an example of how this is done).

**Comment by rib** [comment]
This PR https://github.com/bgourlie/asm6502/pull/12 adds a `ca65` assembler tool which maybe helps address this
