### ISSUE TITLE
Runnings tests from the root directory

### ISSUE THREAD

**Issue by simon-whitehead** [bgourlie/asm6502#5]
Hi,

I am going to start having a little play with your repository :)

As a heads up, to get the tests running from the root directory I had to make a few changes.

Firstly, all of the named parsers required a `pub` access modifier for the tests to recognise them. I was getting lots of this:

```
error[E0425]: unresolved name `mnemonic`
  --> src\parser\tests.rs:31:22
   |
31 |         let result = mnemonic($input.as_bytes());
   |                      ^^^^^^^^ unresolved name
...
68 |     assert_mnemonic_parse!("DEY", Mnemonic::Dey);
   |     --------------------------------------------- in this macro invocation
```

Adding `pub` to them all resolves this.

Also the `parse_lines` test on line 270 of `src/parser/tests.rs` throws an error because:

```
error[E0255]: a value named `parse_lines` has already been imported in this module
   --> src\parser\tests.rs:270:1
    |
2   | use parser::*;
    |     ---------- previous import of `parse_lines` here
...
270 | fn parse_lines() {
    | ^ `parse_lines` was already imported

error: aborting due to previous error
```

Changing this to `parse_lines_test` fixed that issue as well. Happy to open a PR for that if you want. Not sure how you're working with this locally - maybe I've broken something? They seem like legitimate compiler errors though.

**Comment by bgourlie** [comment]
>I am going to start having a little play with your repository :)

Awesome 👍 :)

>As a heads up, to get the tests running from the root directory I had to make a few changes.

How are you running the tests? `cargo test` is the recommended approach. It works for me and is working on [the latest travis-ci build](https://travis-ci.org/bgourlie/asm6502/jobs/196270774)

**Comment by bgourlie** [comment]
Ah, I figured it out. You will need to use the rust beta or nightly branch. I think a change related to proc macros (which will stabilize in 1.15) is what's causing this, although I can't pinpoint exactly what it's depending on (nom itself doesn't use proc macros to my knowledge). It's weird for sure. Do you use rustup?

**Comment by simon-whitehead** [comment]
I'm using `cargo test` - just from the root directory. Hrrmmm. This is my Windows PC at work (I err.... had some free time this morning? :smiley:) .. maybe that is contributing. I can try on my Mac later tonight at home.

I used `rustup` to update my stable locally. I didn't see any requirement for nightly. Maybe I'll try nightly.

**Comment by simon-whitehead** [comment]
Ah right. Can do nightly if its required. I didn't realise - sorry.

**Comment by bgourlie** [comment]
Yup, if you `rustup default beta` it should work. I'll update the README. My bad!

**Comment by simon-whitehead** [comment]
No problem at all. I should have tried that first I guess. Thanks!
