### ISSUE TITLE
Improve parser error messages

### ISSUE THREAD

**Issue by bgourlie** [bgourlie/asm6502#6]
When a parsing operation results in an error or an incomplete result, we display nom's error message verbatim. These error messages aren't intuitive, so it would be nice to improve them.

nom supports custom error types as described on its [README](https://github.com/Geal/nom). Displaying line numbers for any errors along with any additional context would be ideal.

**Comment by rib** [comment]
This PR https://github.com/bgourlie/asm6502/pull/12 may help address this issue

E.g. with this code:
```asm
JSR $411E ; test
JMP $4103
PHA
TXA
Foo:
PHA
--- <-- invalid syntax
TYA
PHA
.DB 0, 0, 0, 0
```

it shows this error now:
```
Failed to tokenize input: 0: at line 7, in Eof:
--- <-- invalid syntax
^
```
